
name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
      - "feature/*"
  workflow_dispatch:

jobs:
  # unit tests
  tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test
